export { check, type CheckOptions } from "./check.js";
export { reachability, type ReachabilityResult, type ReachabilityOptions } from "./reachability.js";
export type { CitationResult, FiredRule } from "./io/evidence.js";
export { loadRules, type RuleSet } from "./rules/load.js";
export type { Verdict } from "./classify/verdict.js";
export type { Fetcher, RawResponse, RungId } from "./fetch/types.js";
export { parseGfmFootnotes } from "./adapters/gfm-footnotes.js";
export { parseClaimsFile, normalizeUrl, joinClaims } from "./io/claims.js";
export { VERSION } from "./version.js";
export { defaultFetcher, type FetcherOptions } from "./fetch/default-fetcher.js";
export { norm } from "./text/normalize.js";
export { toText } from "./text/extract.js";
export { THRESHOLDS } from "./classify/thresholds.js";
export { validateClaims, type ClaimProblem } from "./io/validate.js";
export { classifyRun, type RunTally, type FailOn } from "./run/classify.js";
export type { Evidence } from "./text/excerpt.js";
export type { Rule } from "./rules/challenge.js";
export type { HostRule } from "./rules/hosts.js";
export type { Document, Footnote } from "./adapters/types.js";
export type { ClaimsFile, ClaimEntry, Joined } from "./io/claims.js";
export type { BuiltinRung } from "./fetch/types.js";
